### ISSUE TITLE
Colors of neovim :term termianl emulator

### ISSUE THREAD

**Issue by mcepl** [ajgrf/parchment#2]
I really like the parchment colour scheme for its subdued simple style, but it completely falls apart when one uses ``:term`` in neovim (and perhaps in vim8 as well?):
![snimek z 2019-02-17 23-46-25](https://user-images.githubusercontent.com/198999/52920586-67783280-330e-11e9-999b-d46653baf689.png)
Suddenly instead of subdued colours I have crazy parrot. Solarized (although otherwise slightly too much for my  taste) has a way more sensible terminal.

**Comment by ajgrf** [comment]
Thanks for the bug report! I just pushed a commit to improve parchment's support for the embedded terminals in vim8 and neovim. Unfortunately there is no way to configure these terminals to use the same colors for both normal and bold text, so parchment's support remains imperfect. Hopefully it is still good enough for you!

**Comment by mcepl** [comment]
Yes, that's MUCH better. Thank you.
