### ISSUE TITLE
This is too subdued on the other hand

### ISSUE THREAD

**Issue by mcepl** [ajgrf/parchment#3]
I really like quiet and non-dramatic colors of this colorscheme, but there are moments, when it is too much. When I have a huge list of (what’s essentially) compilation errors in the QuickFix window, it is mostly impossible to see where the cursor is. Given those lists are very long (this one is from [LangTool](https://github.com/Konfekt/vim-langtool), the grammar checker), I have to switch to solarized to use it at all:
![Snímek z 2020-06-18 17-42-30](https://user-images.githubusercontent.com/198999/85042750-dd530f00-b18b-11ea-976d-8bd26d455101.png)
(Actually there is tiny difference, because the text is slightly bolder, but it is really hard to see)

Solarized has much more functional results:
![Snímek z 2020-06-18 17-42-22](https://user-images.githubusercontent.com/198999/85042795-ea6ffe00-b18b-11ea-980e-b7f120141849.png)

I wouldn’t mind (too keep everything simple) completely reversed text (white on the black background).

**Comment by ajgrf** [comment]
Thanks for the bug report. I'm happy to fix this for you, but I'm not quite sure how to reproduce your problem.

If you could identify the face names that need to be changed that would help me a lot. To do so, put your cursor over the text, press `S-M-x` and type `(face-at-point t t)`. A list of text faces should be printed in the minibuffer.

**Comment by mcepl** [comment]
> Thanks for the bug report. I'm happy to fix this for you, but I'm not quite sure how to reproduce your problem.
> 
> If you could identify the face names that need to be changed that would help me a lot. To do so, put your cursor over the text, press `S-M-x` and type `(face-at-point t t)`. A list of text faces should be printed in the minibuffer.

This is the problem in ``vim`` (actually ``neovim``), not ``emacs``.

**Comment by ajgrf** [comment]
Oh, sorry about that. I had only heard of langtool as an emacs package before. I'll look into it.

**Comment by ajgrf** [comment]
After looking into this further, I've concluded that the quickfix window reuses the `Search` highlight group for this. So changing it would also change the appearance of all search patterns. I'm not willing change such a central element of the theme for the sake of fonts that don't differentiate their bold variant very well.

If you'd rather keep using your current font, you could always add your own customizations directly to your vimrc file. For example:

    colorscheme parchment
    highlight Search ctermbg=12 guibg=#cceeff

**Comment by ajgrf** [comment]
Nevermind, newer versions of vim and neovim have `QuickFixLine` to set this separately from `Search`. So it looks like I can fix it after all.

**Comment by mcepl** [comment]
Well, it is slightly of the colorscheme pallet, but at least it is nicely visible. Thank you.
