### ISSUE TITLE
Support also treesitter colors

### ISSUE THREAD

**Issue by mcepl** [ajgrf/parchment#4]
neovim developers work hard now on support treesitter (see supporting project https://github.com/nvim-treesitter/nvim-treesitter, but the main support is directly inside of the main source tree), I am not an Emacs user, so I am not sure with the situation there, but at least there is [emacs-tree-sitter](https://github.com/ubolonton/emacs-tree-sitter) package (now on MELPA).

There is some documentation in [neovim doc file](https://github.com/neovim/neovim/blob/master/runtime/doc/treesitter.txt) and there seems to [quite an interest in it on Reddit](https://www.reddit.com/r/neovim/search?q=treesitter&restrict_sr=1), but I am not exactly sure what exactly it means for the color schemes like this project.

[This discussion](https://www.reddit.com/r/neovim/comments/jis995/recommended_colorscheme_for_treesitter/) seems to be relevant.

**Comment by ajgrf** [comment]
I don't have time to work on this right now, but I'll leave the issue open because it seems like a good idea that I should work on eventually. PRs welcome.

**Comment by ajgrf** [comment]
Closing this now because I don't plan to continue working on `parchment-theme`. See the README for the deprecation notice and suggested migration path for Emacs users.

**Comment by mcepl** [comment]
> Closing this now because I don't plan to continue working on `parchment-theme`. See the README for the deprecation notice and suggested migration path for Emacs users.

For vim/neovim users you may mention https://github.com/plan9-for-vimspace/acme-colors which seems like having similar goals of the project.

**Comment by ajgrf** [comment]
Thanks for the suggestion! I've added it to the README.
